### ISSUE TITLE
pg::golomb::encode unsafe output iterator

### ISSUE THREAD

**Issue by CrustaShrimp** [PG1003/golomb#1]
The encode function has a generic type OutputIt.
The name suggests it should be an output iterator.
Maybe a concept/requirement can be used to force the OutputIt to at least be an output iterator of correct type (by using std::output_iterator)
However, since the size of the output is unknown, there is a risk of running out of space in the container.

In the examplecode test.cpp, std::back_inserters are used everywhere. This is always* safe.
However, suppose the vector `result` was preallocated or was an std::array instead, then it would be unsafe since it might occur that the result takes more than the preallocated amount of elements.
There is no way to know beforehand, and there is no way to test currently, since inside the function, the original container cannot be accessed. 

Two suggested solutions:

- Make the parameter a reference to a container and use the std::back_inserter within the API, so e.g. line 201:

```
encoder< OutputIt, OutputDataT > e( output, k );
```
Turns into
```
encoder< std::back_inserter<OutputContainer>, OutputDataT > e( std::back_inserter<outputcontainer>, k );
```
, where outputcontainer is required to be some container.
This is still unsafe, since a std::array might not have the correct size either, and the std::back_inserter will fail at some point

- return a container by moving it out of the encode function. In this way, the correct size is guaranteed.
The type of container could be specified by template parameter (with requirement of being a container with back_inserter)

**Comment by PG1003** [comment]
The encode/decode API is inspired by the STL algorithm functions e.g. `std::transform`.
Returning a container will constrain the usage of the library.

The current API allows you to customize the input/output handling with the use of fancy iterators, such as using the `std::back_inserter` as is done in the tests. Also the golomb utility use a custom input and output iterator that wrap a file handle to read and write data.

I'm not sure how to improve the safety of the encoder output. I've thought about this before and the ideas I had added more complexity or reduced the flexibility of the API.
At the moment it is the responsibility of the caller to avoid buffer overflows when encoding data.
For now I think a `std::back_inserter` or some kind of fancy iterator that has bounds checking should do.

The issue for the decoder output is not that big since it is likely known what the number of values the encoded data contains.

**Comment by CrustaShrimp** [comment]
Agreed, it is very difficult to improve safety. Since the out of bounds error is quite clear and adding safety significantly degeneralizes the API, the issue can be closed
